{
 "title": "Cloudflare - GraphQL Metrics",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "zone", "label": "zone", "query": { "query": "label_values(zone_tag)" } }
  ]
 },
 "panels": [
  {
   "title": "Cloudflare - Pageviews by Zone",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "cf_http_requests_basic{type=\"pageviews\"}",
     "legendFormat": "{{type}}: {{zone_tag}}"
    }
   ]
  },
  {
   "title": "Cloudflare - Bytes by Zone",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "cf_http_requests_basic{type=\"bytes\"}",
     "legendFormat": "{{type}}: {{zone_tag}}"
    }
   ]
  },
  {
   "title": "Cloudflare - Bytes by Zone",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "cf_http_requests_basic{type=\"requests\"}",
     "legendFormat": "{{type}}: {{zone_tag}}"
    }
   ]
  },
  {
   "title": "Cloudflare - Unique Visitor by Zone",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "cf_http_requests_basic{type=\"uniq\"}",
     "legendFormat": "{{type}}: {{zone_tag}}"
    }
   ]
  },
  {
   "title": "Cloudflare - HTTP Status Code",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "cf_http_requests_status_code{zone_tag=\"$zone\"}",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "Cloudflare - Requests by Country by Zone",
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 8 },
   "valueName": "total",
   "targets": [
    {
     "expr": "cf_http_requests_country_requests{zone_tag=\"$zone\"}",
     "legendFormat": "{{country}}"
    }
   ]
  },
  {
   "title": "Cloudflare - Bytes by Country by Zone",
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 8 },
   "valueName": "current",
   "targets": [
    {
     "expr": "cf_http_requests_country_bytes{zone_tag=\"$zone\"}",
     "legendFormat": "{{country}}"
    }
   ]
  },
  {
   "title": "Cloudflare - Bytes by Content Type",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 18 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "cf_http_requests_content_type_bytes{zone_tag=\"$zone\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Cloudflare - Requests by Content Type",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 8, "w": 10, "x": 10, "y": 18 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "cf_http_requests_content_type_request{zone_tag=\"$zone\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Cloudflare - Firewall Events",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cf_firewall_event{zone_tag=\"$zone\"}",
     "legendFormat": "{{zone_tag}}"
    }
   ]
  },
  {
   "title": "Cloudflare - Bytes Requested in Main Colocation",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(cf_colo_requests{zone_tag=\"$zone\", type=\"bytes\"}[5m])",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Cloudflare - Count Requested in Main Colocation",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cf_colo_requests{zone_tag=\"$zone\", type=\"count\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Cloudflare - Visits in Main Colocation",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cf_colo_requests{type=\"visit\",zone_tag=\"$zone\"}",
     "legendFormat": "{{type}}"
    }
   ]
  }
 ]
}